"""
Pydantic schemas for the Business Intelligence Agent API.
"""

from typing import Any

from pydantic import BaseModel, Field


# ============================================================
# Agent Query Schemas
# ============================================================

class AgentQueryRequest(BaseModel):
    """Request body for an agent query."""

    question: str = Field(
        ...,
        min_length=3,
        description="Natural-language business question.",
    )


class AgentTraceEvent(BaseModel):
    """Single agent execution trace event."""

    trace_id: str
    step: int
    event: str
    timestamp: float
    data: dict[str, Any] = Field(default_factory=dict)


class AgentEvidence(BaseModel):
    """Evidence used to generate the final answer."""

    source: str
    data: Any


class AgentQueryResponse(BaseModel):
    """Response returned by the agent API."""

    trace_id: str
    status: str
    question: str
    intent: str
    answer: str
    iterations: int
    total_duration_ms: float | None
    error: str | None
    evidence: list[AgentEvidence]
    trace: list[AgentTraceEvent]


# ============================================================
# Business Dashboard Schemas
# ============================================================

class DashboardKPIs(BaseModel):
    """Business intelligence dashboard KPI metrics."""

    total_revenue: float
    total_orders: int
    total_customers: int
    completed_orders: int
    average_order_value: float
    return_rate: float
    cancellation_rate: float


class RevenueTrendItem(BaseModel):
    """Monthly revenue trend item."""

    month: str
    revenue: float


class CategoryRevenueItem(BaseModel):
    """Revenue generated by product category."""

    category: str
    revenue: float


class TopProductItem(BaseModel):
    """Top-performing product."""

    product_name: str
    category: str
    units_sold: int
    revenue: float


class SegmentPerformanceItem(BaseModel):
    """Customer segment performance metrics."""

    segment_name: str
    customers: int
    orders: int
    revenue: float


class OrderStatusItem(BaseModel):
    """Order status distribution."""

    status: str
    order_count: int


class DashboardSummaryResponse(BaseModel):
    """Complete business intelligence dashboard response."""

    kpis: DashboardKPIs
    revenue_trend: list[RevenueTrendItem]
    category_revenue: list[CategoryRevenueItem]
    top_products: list[TopProductItem]
    segment_performance: list[SegmentPerformanceItem]
    order_status: list[OrderStatusItem]